.TH FLUX 1 "January 2024" "Version 0.1.0" "User Commands"
.SH NAME
flux \- An advanced, customizable shell for modern systems
.SH SYNOPSIS
.B flux
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B flux
is a modern shell implementation written in Rust that combines the power of traditional Unix shells with modern features and customization options.
.PP
It provides features such as customizable prompts with git integration, theme support, path and command aliasing, environment variable management, and command history.
.SH CONFIGURATION
Configuration file is located at:
.IP
Unix: $XDG_CONFIG_HOME/sh.lrr.flux/config.fl
.br
Windows: %APPDATA%\\sh.lrr.flux\\config.fl
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display help message
.TP
.BR \-v ", " \-\-version
Display version information
.TP
.BR config
Reconfigure the shell (removes existing config and generates new)
.TP
.BR plugin
Plugin management commands
.TP
.BR env
Environment variable management
.SH AUTHOR
Written by 0x800a6
.SH BUGS
Report bugs at: https://github.com/0x800a6/flux/issues
.SH COPYRIGHT
Copyright \(co 2024 0x800a6. License MIT. 