blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://flux.choco.rip/pages/community
    about: For general questions and discussions
  - name: Documentation
    url: https://flux.choco.rip
    about: Make sure to check our documentation first
