blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://flux.lrr.sh/pages/community
    about: For general questions and discussions
  - name: Documentation
    url: https://flux.lrr.sh
    about: Make sure to check our documentation first
