name: Feature Request
description: Suggest a new feature for Flux Shell
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide the details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
      placeholder: I'm trying to accomplish X, but...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - Command Line Interface
        - Configuration
        - Performance
        - Customization
        - Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Other ways to solve this problem...
