title: Flux Shell
description: An advanced, customizable shell for modern systems
baseurl: ""
url: "https://flux.lrr.sh"

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Navigation
navigation:
  - title: Blog
    url: /blog/
  - title: Community
    url: /community/

# GitHub
github:
  repository_url: https://github.com/0x800a6/flux
  zip_url: https://github.com/0x800a6/flux/archive/refs/heads/master.zip
  tar_url: https://github.com/0x800a6/flux/archive/refs/heads/master.tar.gz 

title: "Flux Shell"
tagline: "A modern shell for modern developers"
description: "Flux Shell is a blazing-fast, customizable shell written in Rust, designed for modern developers"
url: "https://flux.lrr.sh"
author: 0x800a6
twitter:
  username: fluxshell
  card: summary_large_image
logo: /assets/images/flux-shell-logo.png
social:
  name: Flux Shell
  links:
    - https://github.com/0x800a6/flux
