name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Add NodeJS and NPM
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Build docs
        run: |
          cd scripts
          node docs.js

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./www
          destination: ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 